---
- hosts: devp
  gather_facts: no
  become: yes
  become_user: root
  remote_user: 206445665

  tasks:

  - name: create start script
    copy:
     src: /vagrant/scripts/files/ibm-ucdagent
     dest: /etc/rc.d/init.d/ibm-ucdagent
     mode: 0777
  - name: set unlevels 5
    file:
     src: /etc/rc.d/init.d/ibm-ucdagent
     dest: /etc/rc.d/rc5.d/S98ibm-ucdagent
     state: link
  - name: set unlevels 4
    file:
     src: /etc/rc.d/init.d/ibm-ucdagent
     dest: /etc/rc.d/rc4.d/S98ibm-ucdagent
     state: link
  - name: set unlevels 3
    file:
     src: /etc/rc.d/init.d/ibm-ucdagent
     dest: /etc/rc.d/rc3.d/S98ibm-ucdagent
     state: link
  - name: start agent
    service:
      name: ibm-ucdagent
      state: started
